### ISSUE TITLE
Uso da classe

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/sped-efd#13]
é possível escrever um estoque com essa classe? vie nos documentos que sim.

**Comment by robmachado** [comment]
Na verdade essas classes foram apenas rascunhadas nada está funcional ou terminado.

**Comment by lpj145** [comment]
Veja o que minha mente incrível conseguiu fazer :smile:

**Comment by robmachado** [comment]
Hehe ... bem tem várias coisas que não irão funcionar tipo as funções abrefecha é claro que está incompleto. Pelo principio do SOLID é recomendável que você crie uma sub class para cada registro. Essa subclass referente ao registro irá, na montagem abrir o bloco, inserir os registros e fechar o bloco co a contagem final. Mas isso é apenas um comentário meu, não vou mexer com isso agora tenho outras prioridades.
