### ISSUE TITLE
Letras maiúsculas bloco 0 - registro 0000

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/sped-efd#428]
Os parâmetros do registro 0000 (bloco 0) estão em minusculo. Os registros restantes estão todos em maiúsculos, posso fazer uma atualização alterando isso ou tem algum motivo especifico?

**Comment by robmachado** [comment]
Guilherme, como essas classes foram feitas por várias mãos existem essas diferenças ESTÉTICAS.

Ao que eu me lembre será indiferente, colocar tanto os parâmetros ou a entrada de dados  em maiúsculas ou minusculas (ou misturado), pois AMBOS serão convertidos para minusculo para validações e montagem das estruturas. 
Ou seja isso é "CASE IGNORE" para esses casos.

**Comment by guicalabria** [comment]
Roberto, 
   Eu estou vendo que as montagens seguem a ordem de criação, não acha que seria interessante se seguisse o nome?
   Pensei em criar um array com a determinada sequencia de campos por versão. E na montagem do arquivo seguir essa sequencia.
   Digo isso para poder pegar a tabela do banco de dados e enviar para a classe diretamente. Nesse caso seria interessante também deixar tudo maiúsculo para bater com a documentação.

**Comment by robmachado** [comment]
Então Guilherme, isso acaba sendo complexo pois os campos não são colocados em ordem numérica propriamente.
Ex.
B001
   B020
      B025
   B020 
   B030
Ou seja tem registros que são ligados uns aos outros

**Comment by guicalabria** [comment]
Você quis dizer registros ou campos?
Minha ideia é organizar os campos para que ao receber uma classe std ou um vetor usar os nomes do campos ao invés da sequencia... 
Os registros serão criados de forma sequencial que o programa fizer, o que eu quero é criar o registro de acordo com o nome dos campos e não a sequencia.
Por exemplo no B020 temos:
01 REG
02 IND_OPER
03 IND_EMIT
04 COD_PART ... etc
Essa é a sequencia correta, certo?
Criando um array (1=>REG,2=>IND_OPER,3=>IND_OPER,4=>COD_PART...etc) será possível receber uma classe ou um array e pegar os campos por nome.
O projeto já faz assim ou o registro é criado pela sequencia que os campos são definidos?

**Comment by robmachado** [comment]
Então o projeto já faz dessa forma mas não com um array mas com um stdClass
Digamos que você obtenha na consulta na  base de dados:
array (REG => 0000,COD_VER => 013,COD_FIN => 0,DT_INI => 01012019,DT_FIN => 31012019,NOME => EMPRESA SA,CNPJ => 023567656000160,CPF => null,UF => SP,IE => 2345678901,COD_MUN => 3518800,IM => 123456,SUFRAMA => nulll,IND_PERFIL => A,IND_ATIV => 0);

Para carregar o registro do bloco 
- extraia o identificador do registro nesse caso '0000', como começa com um numero, então combine com a letra Z
$method = "Z{$registro}"; //resulta em Z0000
- monte o stdClass com os demais dados :
  . remova o registro do array
  . converta o array restante em stdClass usando json_decode(json_encode) 
bloco0->$method($std);
Pronto esse registro já foi criado. 
É importante salientar que a melhor forma de manter esses registro em base de dados deve levar em consideração o uso de NoSQL e/ou mascaras JSON pode facilitar em muito o carregamento

**Comment by robmachado** [comment]
Na verdade pode até deixar o REG no array (ou no stdClass) pois o mesmo será desconsiderado na construção do registro dentro do bloco, pois não é um campo requerido como parâmetro mas sim para determinar qual método deverá ser utilizado pela classe construtora.

**Comment by robmachado** [comment]
Esse é um exemplo do que eu tenho em mente
CREATE TABLE `blocoB` (
  `id` int(11) NOT NULL,
  `data` datetime NOT NULL,
  `reg` varchar(5) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` json NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='EFD ICMS/IPI Bloco B';
