### ISSUE TITLE
C130 VL_ IRRF

### ISSUE THREAD

**Issue by Nahapa** [nfephp-org/sped-efd#445]
Função C130, VL_IRRF esta com espaço na variável, ficando VL_ IRRF , apesar que a documentação também esta, então provavelmente um erro gerou o outro.

![image](https://user-images.githubusercontent.com/34748506/68045210-bf49a480-fcb7-11e9-80d4-b9aa4d11f99a.png)
![image](https://user-images.githubusercontent.com/34748506/68045234-c7a1df80-fcb7-11e9-9f96-ae2e07adb75d.png)

**Comment by robmachado** [comment]
Corrigido!
