### ISSUE TITLE
ICMS C510

### ISSUE THREAD

**Issue by Nahapa** [nfephp-org/sped-efd#456]
Faltando os campos VL_BC_ICMS_ST, COD_CTA na função C510

![image](https://user-images.githubusercontent.com/34748506/68218324-e3142f80-ffc2-11e9-9b47-e6d3220b1e50.png)
![image](https://user-images.githubusercontent.com/34748506/68218440-13f46480-ffc3-11e9-9483-d617bcfa3b84.png)

**Comment by robmachado** [comment]
Boa ! continue assim que vamos deixar o código limpo  e funcional :+1:

**Comment by robmachado** [comment]
Corrigido!
