### ISSUE TITLE
Versão 014

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/sped-efd#463]
Estou atualizando para a versão 014 do layout, você tem alguma previsão para atualização ou posso incluir os novos registros e criar um pull request?

Ainda estou avaliando porém até agora tenho para criar:
0002
C180
C185
C330
C380
C430
C480
C500 - NOVOS CAMPOS
C591
C595
C597
C810
C815
C870
C880
G130 - NOVOS CAMPOS
G140 - NOVOS CAMPOS
H030
1010 - NOVOS CAMPOS
1391 - NOVOS CAMPOS
1250
1255

**Comment by robmachado** [comment]
Oi Guilherme, claro manda VER irmão !

**Comment by guicalabria** [comment]
Roberto, verifiquei agora que algumas tabelas estão com os campos em minúsculos como a z0000 e outros com campos em maiúsculos .
Qual é o correto para usar?

**Comment by robmachado** [comment]
Guilerme; 
A nomenclatura dos campos podem estar em maiúsculas ou em minusculas, tanto na entrada de dados como nas classes dos Elementos, isso deve ser **indiferente**, pois em ambos os casos é feito um CASE LOWER. E o arquivo EFD em si é posicional .
Apenas as constantes REG tem que estar conforme o manual.

**Comment by guicalabria** [comment]
Ok, mas acho que ficaria melhor se fosse definido um padrão.

**Comment by robmachado** [comment]
Ok então usamos como indicado na documentação do EFD como padrão torna mais legivel para quem for ajudar

**Comment by guicalabria** [comment]
Roberto, continuo trabalho nessa classe, existem algumas mudanças, por exemplo na tabela 0190 não é mais exigido que UNID e DESCR sejam iguais , fonte: Guia Prático EFD-ICMS/IPI – Versão 3.0.2 Atualização: 21 de maio de 2019.
Devo realizar alguns commits depois de finalizar isso nesse final de semana.

**Comment by robmachado** [comment]
Mande ver, irmão !
