### ISSUE TITLE
Contribuição elemento c100

### ISSUE THREAD

**Issue by ADSRP** [nfephp-org/sped-efd#469]
A validação do campo IND_PGTO e IND_FRT do elemento C100, não esta de acordo com o guia.

**Comment by robmachado** [comment]
Quanto ao IND_PGTO eu concordo está faltando o 9
Mas quanto ao IN_FRT me parece correto !!!

*Campo 17 (IND_FRT) - Valores válidos: [0, 1, 2, 9]
Preenchimento: Em operações tais como: remessas simbólicas, faturamento simbólico, transporte próprio, venda balcão,
informar o código “9 - sem frete”, ou seja, operações sem cobrança de frete.
Quando houver transporte com mais de um responsável pelo seu pagamento, deve ser informado o indicador do frete relativo
ao responsável pelo primeiro percurso.
A partir de 01/01/2018: Valores válidos: [0, 1, 2, 3, 4, 9]*

**Comment by robmachado** [comment]
O IND_PGTO foi corrigido !!

**Comment by ADSRP** [comment]
> O IND_PGTO foi corrigido !!

**Comment by ADSRP** [comment]
> O IND_PGTO foi corrigido !!

Obrigado

**Comment by ADSRP** [comment]
> O IND_PGTO foi corrigido !!

A correção foi no ICMSIPI, o erro é no Contribuicoes

**Comment by robmachado** [comment]
Estava "oculta essa informação" seja mais claro Erro - Sped-Contribuições IND_PGTO ai fica melhor :+1:

**Comment by robmachado** [comment]
Corrigido EFD-Contribuicoes C100 IND_PGTO e IND_FRT

**Comment by ADSRP** [comment]
> Estava "oculta essa informação" seja mais claro Erro - Sped-Contribuições IND_PGTO ai fica melhor 👍

Certo, obrigado
