### ISSUE TITLE
Bloco 9 já foi implementado?

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-efd#478]
Não encontrei na documentação nem no código-fonte sobre o Bloco 9. Já foi implementado? Ou tem alguma forma de gerar ele a apartir de cada bloco respectivo?

**Comment by eumanito** [comment]
Como retorno esses registros em cada bloco?

Por exemplo no bloco H faço assim para obter os registros:
$bH->get(); 

Teria algum método assim?
$bH->getTotalize();

**Comment by robmachado** [comment]
Não entendi sua pergunta !! Que Totalize é esse que você está colocando ???

Cada bloco é gerado com o seu próprio fechamento (ou subtotalização)
A totalização com o bloco 9 é gerada pela classe EFDICMS

**Comment by eumanito** [comment]
Ahhhhhhhhh bom, eu não sabia que tinha que instanciar os blocos e repassá-los para a classe EFDICMS!
Pois as classes de cada bloco permitem acessar o método get(), eu estava montando na mão!

Agora entendi.
Obrigado.
