### ISSUE TITLE
Versão do php

### ISSUE THREAD

**Issue by tiagokb** [nfephp-org/sped-efd#512]
Teria como fazer uma versão compatível com o php 7.3 ?

**Comment by robmachado** [comment]
Infelizmente NÃO !!  
Este ano todas as versões de todo o echo sistema (todos os pacotes do nfephp-org) serão ajustados  para php v8.0 como mínimo.
Se quiser fazer para outras versões do PHP terá de fazer seu próprio fork e mante-lo pessoalmente.

**Comment by fillipenorton** [comment]
Atualmente o pacote não funciona com a versão 7.4 ?

**Comment by robmachado** [comment]
Funciona sim com a 7.4
