### ISSUE TITLE
Parser para o EFD Contribuições

### ISSUE THREAD

**Issue by vvanio** [nfephp-org/sped-efd#517]
Gostaria de contribuir, ajustando o Parser ou desenvolvendo algo similar para fazer a leitura do EFD Contribuições.
Podem me orientar onde posso obter ou como gerar os arquivos:
structure_EFDICMS_{version}.txt
structure_EFDICMS_BLOCKS_{version}.txt
structure_EFDICMS_ELEMENTS_{version}.json

Grato.

**Comment by robmachado** [comment]
Esses arquivos foram construídos manualmente com base nos dados do guia pratico
