### ISSUE TITLE
Evento R2020 (EvtServPrest)

### ISSUE THREAD

**Issue by ArthurPerdSantos** [nfephp-org/sped-efd#541]
Boa noite, estou com um problema no evento R2020. Estou recebendo a seguinte mensagem de erro no momento de comparação do com xml do evento.
Este XML não é válido. Element '{http://www.reinf.esocial.gov.br/schemas/evtPrestadorServicos/v2_01_02}vlrServicos25': [facet 'pattern'] The value '1' is not accepted by the pattern '[0-9]{1,12}[,][0-9]{2}'.

Esse campo "vlrServicos25" não é um campo obrigatório, e não faço o envio dele, porém está me retornando que ele não segue o padrão correto, a baixo está os dados que estou enviando para o evento. Agradeço se tiver como me ajudar.

{
    "modo": "INC",
    "perapur": "2023-08",
    "indretif": 1,
    "tpInscEstabPrest": 1,
    "nrInscEstabPrest": "26205129000120",
    "tpInscTomador": "1",
    "nrInscTomador": "31901174000159",
    "indobra": 0,
    "vlrTotalBruto": 1000,
    "vlrTotalBaseRet": 1000,
    "vlrTotalRetPrinc": 100,
    "nfs": [
        {
            "serie": "BOB12",
            "numDocto": "1234567890",
            "dtEmissaoNF": "2023-08-01",
            "vlrBruto": 1000,
            "infoTpServ": [
                {
                    "tpServico": "100000007",
                    "vlrBaseRet": 1000,
                    "vlrRetencao": 100
                }
            ]
        }
    ]
}

**Comment by robmachado** [comment]
Você esta no repositório errado !!! evento R2020 é do sped-efdreinf !!!
